/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class us_toadlet_pad_Engine */

#ifndef _Included_us_toadlet_pad_Engine
#define _Included_us_toadlet_pad_Engine
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     us_toadlet_pad_Engine
 * Method:    destroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_us_toadlet_pad_Engine_destroy
  (JNIEnv *, jobject);

/*
 * Class:     us_toadlet_pad_Engine
 * Method:    installHandlers
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_us_toadlet_pad_Engine_installHandlers
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
