/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class us_toadlet_flick_NInputDeviceListener */

#ifndef _Included_us_toadlet_flick_NInputDeviceListener
#define _Included_us_toadlet_flick_NInputDeviceListener
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     us_toadlet_flick_NINputDeviceListener
 * Method:    inputDetected
 * Signature: (Lus/toadlet/flick/InputData;)V
 */
JNIEXPORT void JNICALL Java_us_toadlet_flick_NInputDeviceListener_inputDetected
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
