/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class us_toadlet_flick_NMotionDeviceListener */

#ifndef _Included_us_toadlet_flick_NMotionDeviceListener
#define _Included_us_toadlet_flick_NMotionDeviceListener
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     us_toadlet_flick_NMotionDeviceListener
 * Method:    motionDetected
 * Signature: (Lus/toadlet/flick/MotionData;)V
 */
JNIEXPORT void JNICALL Java_us_toadlet_flick_NMotionDeviceListener_motionDetected
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
