# Attempt to find toadlet
# Defines:
#
#  TOADLET_FOUND	- system has toadlet
#  TOADLET_INCLUDE_DIR	- path to the toadlet include directory
#  TOADLET_LIBRARY_DIR	- path to the toadlet library installation dir
#
# Also defines each toadlet library individually, both dynamic and static (_S) versions. Release chosen first, then debug (_D):
#  TOADLET_EGG_LIB
#  TOADLET_FLICK_LIB
#  TOADLET_FLICK_HTCMOTIONDETECTOR_LIB
#  TOADLET_FLICK_IOSMOTIONDETECTOR_LIB
#  TOADLET_FLICK_SAMSUNGMOTIONDETECTOR_LIB
#  TOADLET_HOP_LIB
#  TOADLET_KNOT_LIB
#  TOADLET_PEEPER_LIB
#  TOADLET_PEEPER_GLRENDERER_LIB
#  TOADLET_PEEPER_D3D9RENDERER_LIB
#  TOADLET_PEEPER_D3DMRENDERER_LIB
#  TOADLET_PEEPER_D3D10RENDERER_LIB
#  TOADLET_PEEPER_D3D11RENDERER_LIB
#  TOADLET_RIBBIT_LIB
#  TOADLET_RIBBIT_ALPLAYER_LIB
#  TOADLET_RIBBIT_MMPLAYER_LIB
#  TOADLET_TADPOLE_LIB
#  TOADLET_TADPOLE_HOP_LIB
#  TOADLET_PAD_LIB

set (TOADLET_FOUND "NO")

# Default search paths
if (WIN32)
	set (HEADER_SEARCH_PATHS
		"C:/Program Files"
		"C:/Program Files/toadlet"
	)
	set (LIBRARY_SEARCH_PATHS
		"C:/Program Files"
		"C:/Program Files/toadlet"
	)
else (WIN32)
	set (HEADER_SEARCH_PATHS
		/usr/include
		/usr/local/include

	)
	set (LIBRARY_SEARCH_PATHS
		/usr/lib 
		/usr/local/lib
	)
endif (WIN32)

# Headers
find_path (TOADLET_INCLUDE_DIR toadlet/toadlet.h PATHS ${HEADER_SEARCH_PATHS})

# Dynamic Libraries
find_library (TOADLET_EGG_LIB NAMES toadlet_egg PATHS ${LIBRARY_SEARCH_PATHS})
find_library (TOADLET_FLICK_LIB NAMES toadlet_flick PATHS ${LIBRARY_SEARCH_PATHS})
find_library (TOADLET_FLICK_HTCMOTIONDETECTOR_LIB NAMES toadlet_flick_htcmotiondetector PATHS ${LIBRARY_SEARCH_PATHS})
find_library (TOADLET_FLICK_IOSMOTIONDETECTOR_LIB NAMES toadlet_flick_iosmotiondetector PATHS ${LIBRARY_SEARCH_PATHS})
find_library (TOADLET_FLICK_SAMSUNGMOTIONDETECTOR_LIB NAMES toadlet_flick_samsungmotiondetector PATHS ${LIBRARY_SEARCH_PATHS})
find_library (TOADLET_HOP_LIB NAMES toadlet_hop PATHS ${LIBRARY_SEARCH_PATHS})
find_library (TOADLET_KNOT_LIB NAMES toadlet_knot PATHS ${LIBRARY_SEARCH_PATHS})
find_library (TOADLET_PEEPER_LIB NAMES toadlet_peeper PATHS ${LIBRARY_SEARCH_PATHS})
find_library (TOADLET_PEEPER_GLRENDERER_LIB NAMES toadlet_peeper_glrenderer PATHS ${LIBRARY_SEARCH_PATHS})
find_library (TOADLET_PEEPER_D3D9RENDERER_LIB NAMES toadlet_peeper_d3d9renderer PATHS ${LIBRARY_SEARCH_PATHS})
find_library (TOADLET_PEEPER_D3DMRENDERER_LIB NAMES toadlet_peeper_d3dmrenderer PATHS ${LIBRARY_SEARCH_PATHS})
find_library (TOADLET_PEEPER_D3D10RENDERER_LIB NAMES toadlet_peeper_d3d10renderer PATHS ${LIBRARY_SEARCH_PATHS})
find_library (TOADLET_PEEPER_D3D11RENDERER_LIB NAMES toadlet_peeper_d3d11renderer PATHS ${LIBRARY_SEARCH_PATHS})
find_library (TOADLET_RIBBIT_LIB NAMES toadlet_ribbit PATHS ${LIBRARY_SEARCH_PATHS})
find_library (TOADLET_RIBBIT_ALPLAYER_LIB NAMES toadlet_ribbit_alplayer PATHS ${LIBRARY_SEARCH_PATHS})
find_library (TOADLET_RIBBIT_MMPLAYER_LIB NAMES toadlet_ribbit_mmplayer PATHS ${LIBRARY_SEARCH_PATHS})
find_library (TOADLET_TADPOLE_LIB NAMES toadlet_tadpole PATHS ${LIBRARY_SEARCH_PATHS})
find_library (TOADLET_TADPOLE_HOP_LIB NAMES toadlet_tadpole_hop PATHS ${LIBRARY_SEARCH_PATHS})
find_library (TOADLET_PAD_LIB NAMES toadlet_pad PATHS ${LIBRARY_SEARCH_PATHS})

# Dynamic Libraries - debug
find_library (TOADLET_EGG_LIB_D NAMES toadlet_egg_d PATHS ${LIBRARY_SEARCH_PATHS})
find_library (TOADLET_FLICK_LIB_D NAMES toadlet_flick_d PATHS ${LIBRARY_SEARCH_PATHS})
find_library (TOADLET_FLICK_HTCMOTIONDETECTOR_LIB_D NAMES toadlet_flick_htcmotiondetector_d PATHS ${LIBRARY_SEARCH_PATHS})
find_library (TOADLET_FLICK_IOSMOTIONDETECTOR_LIB_D NAMES toadlet_flick_iosmotiondetector_d PATHS ${LIBRARY_SEARCH_PATHS})
find_library (TOADLET_FLICK_SAMSUNGMOTIONDETECTOR_LIB_D NAMES toadlet_flick_samsungmotiondetector_d PATHS ${LIBRARY_SEARCH_PATHS})
find_library (TOADLET_HOP_LIB_D NAMES toadlet_hop_d PATHS ${LIBRARY_SEARCH_PATHS})
find_library (TOADLET_KNOT_LIB_D NAMES toadlet_knot_d PATHS ${LIBRARY_SEARCH_PATHS})
find_library (TOADLET_PEEPER_LIB_D NAMES toadlet_peeper_d PATHS ${LIBRARY_SEARCH_PATHS})
find_library (TOADLET_PEEPER_GLRENDERER_LIB_D NAMES toadlet_peeper_glrenderer_d PATHS ${LIBRARY_SEARCH_PATHS})
find_library (TOADLET_PEEPER_D3D9RENDERER_LIB_D NAMES toadlet_peeper_d3d9renderer_d PATHS ${LIBRARY_SEARCH_PATHS})
find_library (TOADLET_PEEPER_D3DMRENDERER_LIB_D NAMES toadlet_peeper_d3dmrenderer_d PATHS ${LIBRARY_SEARCH_PATHS})
find_library (TOADLET_PEEPER_D3D10RENDERER_LIB_D NAMES toadlet_peeper_d3d10renderer_d PATHS ${LIBRARY_SEARCH_PATHS})
find_library (TOADLET_PEEPER_D3D11RENDERER_LIB_D NAMES toadlet_peeper_d3d11renderer_d PATHS ${LIBRARY_SEARCH_PATHS})
find_library (TOADLET_RIBBIT_LIB_D NAMES toadlet_ribbit_d PATHS ${LIBRARY_SEARCH_PATHS})
find_library (TOADLET_RIBBIT_ALPLAYER_LIB_D NAMES toadlet_ribbit_alplayer_d PATHS ${LIBRARY_SEARCH_PATHS})
find_library (TOADLET_RIBBIT_MMPLAYER_LIB_D NAMES toadlet_ribbit_mmplayer_d PATHS ${LIBRARY_SEARCH_PATHS})
find_library (TOADLET_TADPOLE_LIB_D NAMES toadlet_tadpole_d PATHS ${LIBRARY_SEARCH_PATHS})
find_library (TOADLET_TADPOLE_HOP_LIB_D NAMES toadlet_tadpole_hop_d PATHS ${LIBRARY_SEARCH_PATHS})
find_library (TOADLET_PAD_LIB_D NAMES toadlet_pad_d PATHS ${LIBRARY_SEARCH_PATHS})

# Static Libraries
find_library (TOADLET_EGG_LIB_S NAMES toadlet_egg_s PATHS ${LIBRARY_SEARCH_PATHS})
find_library (TOADLET_FLICK_LIB_S NAMES toadlet_flick_s PATHS ${LIBRARY_SEARCH_PATHS})
find_library (TOADLET_FLICK_HTCMOTIONDETECTOR_LIB_S NAMES toadlet_flick_htcmotiondetector_s PATHS ${LIBRARY_SEARCH_PATHS})
find_library (TOADLET_FLICK_IOSMOTIONDETECTOR_LIB_S NAMES toadlet_flick_iosmotiondetector_s PATHS ${LIBRARY_SEARCH_PATHS})
find_library (TOADLET_FLICK_SAMSUNGMOTIONDETECTOR_LIB_S NAMES toadlet_flick_samsungmotiondetector_s PATHS ${LIBRARY_SEARCH_PATHS})
find_library (TOADLET_HOP_LIB_S NAMES toadlet_hop_s PATHS ${LIBRARY_SEARCH_PATHS})
find_library (TOADLET_KNOT_LIB_S NAMES toadlet_knot_s PATHS ${LIBRARY_SEARCH_PATHS})
find_library (TOADLET_PEEPER_LIB_S NAMES toadlet_peeper_s PATHS ${LIBRARY_SEARCH_PATHS})
find_library (TOADLET_PEEPER_GLRENDERER_LIB_S NAMES toadlet_peeper_glrenderer_s PATHS ${LIBRARY_SEARCH_PATHS})
find_library (TOADLET_PEEPER_D3D9RENDERER_LIB_S NAMES toadlet_peeper_d3d9renderer_s PATHS ${LIBRARY_SEARCH_PATHS})
find_library (TOADLET_PEEPER_D3DMRENDERER_LIB_S NAMES toadlet_peeper_d3dmrenderer_s PATHS ${LIBRARY_SEARCH_PATHS})
find_library (TOADLET_PEEPER_D3D10RENDERER_LIB_S NAMES toadlet_peeper_d3d10renderer_s PATHS ${LIBRARY_SEARCH_PATHS})
find_library (TOADLET_PEEPER_D3D11RENDERER_LIB_S NAMES toadlet_peeper_d3d11renderer_s PATHS ${LIBRARY_SEARCH_PATHS})
find_library (TOADLET_RIBBIT_LIB_S NAMES toadlet_ribbit_s PATHS ${LIBRARY_SEARCH_PATHS})
find_library (TOADLET_RIBBIT_ALPLAYER_LIB_S NAMES toadlet_ribbit_alplayer_s PATHS ${LIBRARY_SEARCH_PATHS})
find_library (TOADLET_RIBBIT_MMPLAYER_LIB_S NAMES toadlet_ribbit_mmplayer_s PATHS ${LIBRARY_SEARCH_PATHS})
find_library (TOADLET_TADPOLE_LIB_S NAMES toadlet_tadpole_s PATHS ${LIBRARY_SEARCH_PATHS})
find_library (TOADLET_TADPOLE_HOP_LIB_S NAMES toadlet_tadpole_hop_s PATHS ${LIBRARY_SEARCH_PATHS})
find_library (TOADLET_PAD_LIB_S NAMES toadlet_pad_s PATHS ${LIBRARY_SEARCH_PATHS})

# Static Libraries - debug
find_library (TOADLET_EGG_LIB_SD NAMES toadlet_egg_sd PATHS ${LIBRARY_SEARCH_PATHS})
find_library (TOADLET_FLICK_LIB_SD NAMES toadlet_flick_sd PATHS ${LIBRARY_SEARCH_PATHS})
find_library (TOADLET_FLICK_HTCMOTIONDETECTOR_LIB_SD NAMES toadlet_flick_htcmotiondetector_sd PATHS ${LIBRARY_SEARCH_PATHS})
find_library (TOADLET_FLICK_IOSMOTIONDETECTOR_LIB_SD NAMES toadlet_flick_iosmotiondetector_sd PATHS ${LIBRARY_SEARCH_PATHS})
find_library (TOADLET_FLICK_SAMSUNGMOTIONDETECTOR_LIB_SD NAMES toadlet_flick_samsungmotiondetector_sd PATHS ${LIBRARY_SEARCH_PATHS})
find_library (TOADLET_HOP_LIB_SD NAMES toadlet_hop_sd PATHS ${LIBRARY_SEARCH_PATHS})
find_library (TOADLET_KNOT_LIB_SD NAMES toadlet_knot_sd PATHS ${LIBRARY_SEARCH_PATHS})
find_library (TOADLET_PEEPER_LIB_SD NAMES toadlet_peeper_sd PATHS ${LIBRARY_SEARCH_PATHS})
find_library (TOADLET_PEEPER_GLRENDERER_LIB_SD NAMES toadlet_peeper_glrenderer_sd PATHS ${LIBRARY_SEARCH_PATHS})
find_library (TOADLET_PEEPER_D3D9RENDERER_LIB_SD NAMES toadlet_peeper_d3d9renderer_sd PATHS ${LIBRARY_SEARCH_PATHS})
find_library (TOADLET_PEEPER_D3DMRENDERER_LIB_SD NAMES toadlet_peeper_d3dmrenderer_sd PATHS ${LIBRARY_SEARCH_PATHS})
find_library (TOADLET_PEEPER_D3D10RENDERER_LIB_SD NAMES toadlet_peeper_d3d10renderer_sd PATHS ${LIBRARY_SEARCH_PATHS})
find_library (TOADLET_PEEPER_D3D11RENDERER_LIB_SD NAMES toadlet_peeper_d3d11renderer_sd PATHS ${LIBRARY_SEARCH_PATHS})
find_library (TOADLET_RIBBIT_LIB_SD NAMES toadlet_ribbit_sd PATHS ${LIBRARY_SEARCH_PATHS})
find_library (TOADLET_RIBBIT_ALPLAYER_LIB_SD NAMES toadlet_ribbit_alplayer_sd PATHS ${LIBRARY_SEARCH_PATHS})
find_library (TOADLET_RIBBIT_MMPLAYER_LIB_SD NAMES toadlet_ribbit_mmplayer_sd PATHS ${LIBRARY_SEARCH_PATHS})
find_library (TOADLET_TADPOLE_LIB_SD NAMES toadlet_tadpole_sd PATHS ${LIBRARY_SEARCH_PATHS})
find_library (TOADLET_TADPOLE_HOP_LIB_SD NAMES toadlet_tadpole_hop_sd PATHS ${LIBRARY_SEARCH_PATHS})
find_library (TOADLET_PAD_LIB_SD NAMES toadlet_pad_sd PATHS ${LIBRARY_SEARCH_PATHS})

# Prevent these from appearing in the regular variable list
mark_as_advanced (
	TOADLET_INCLUDE_DIR
	TOADLET_LIBRARY_DIR
	TOADLET_EGG_LIB 
	TOADLET_FLICK_LIB 
	TOADLET_FLICK_HTCMOTIONDETECTOR_LIB 
	TOADLET_FLICK_IOSMOTIONDETECTOR_LIB 
	TOADLET_FLICK_SAMSUNGMOTIONDETECTOR_LIB 
	TOADLET_HOP_LIB 
	TOADLET_KNOT_LIB 
	TOADLET_PEEPER_LIB 
	TOADLET_PEEPER_GLRENDERER_LIB 
	TOADLET_PEEPER_D3D9RENDERER_LIB 
	TOADLET_PEEPER_D3DMRENDERER_LIB 
	TOADLET_PEEPER_D3D10RENDERER_LIB 
	TOADLET_PEEPER_D3D11RENDERER_LIB 
	TOADLET_RIBBIT_LIB 
	TOADLET_RIBBIT_ALPLAYER_LIB 
	TOADLET_RIBBIT_MMPLAYER_LIB 
	TOADLET_TADPOLE_LIB 
	TOADLET_TADPOLE_HOP_LIB 
	TOADLET_PAD_LIB 
	TOADLET_EGG_LIB_D 
	TOADLET_FLICK_LIB_D 
	TOADLET_FLICK_HTCMOTIONDETECTOR_LIB_D 
	TOADLET_FLICK_IOSMOTIONDETECTOR_LIB_D 
	TOADLET_FLICK_SAMSUNGMOTIONDETECTOR_LIB_D 
	TOADLET_HOP_LIB_D 
	TOADLET_KNOT_LIB_D 
	TOADLET_PEEPER_LIB_D 
	TOADLET_PEEPER_GLRENDERER_LIB_D 
	TOADLET_PEEPER_D3D9RENDERER_LIB_D 
	TOADLET_PEEPER_D3DMRENDERER_LIB_D 
	TOADLET_PEEPER_D3D10RENDERER_LIB_D 
	TOADLET_PEEPER_D3D11RENDERER_LIB_D 
	TOADLET_RIBBIT_LIB_D 
	TOADLET_RIBBIT_ALPLAYER_LIB_D 
	TOADLET_RIBBIT_MMPLAYER_LIB_D 
	TOADLET_TADPOLE_LIB_D 
	TOADLET_TADPOLE_HOP_LIB_D 
	TOADLET_PAD_LIB_D 
	TOADLET_EGG_LIB_S 
	TOADLET_FLICK_LIB_S 
	TOADLET_FLICK_HTCMOTIONDETECTOR_LIB_S 
	TOADLET_FLICK_IOSMOTIONDETECTOR_LIB_S 
	TOADLET_FLICK_SAMSUNGMOTIONDETECTOR_LIB_S 
	TOADLET_HOP_LIB_S 
	TOADLET_KNOT_LIB_S 
	TOADLET_PEEPER_LIB_S 
	TOADLET_PEEPER_GLRENDERER_LIB_S 
	TOADLET_PEEPER_D3D9RENDERER_LIB_S 
	TOADLET_PEEPER_D3DMRENDERER_LIB_S 
	TOADLET_PEEPER_D3D10RENDERER_LIB_S 
	TOADLET_PEEPER_D3D11RENDERER_LIB_S 
	TOADLET_RIBBIT_LIB_S 
	TOADLET_RIBBIT_ALPLAYER_LIB_S 
	TOADLET_RIBBIT_MMPLAYER_LIB_S 
	TOADLET_TADPOLE_LIB_S 
	TOADLET_TADPOLE_HOP_LIB_S 
	TOADLET_PAD_LIB_S 
	TOADLET_EGG_LIB_SD 
	TOADLET_FLICK_LIB_SD 
	TOADLET_FLICK_HTCMOTIONDETECTOR_LIB_SD 
	TOADLET_FLICK_IOSMOTIONDETECTOR_LIB_SD 
	TOADLET_FLICK_SAMSUNGMOTIONDETECTOR_LIB_SD 
	TOADLET_HOP_LIB_SD 
	TOADLET_KNOT_LIB_SD 
	TOADLET_PEEPER_LIB_SD 
	TOADLET_PEEPER_GLRENDERER_LIB_SD 
	TOADLET_PEEPER_D3D9RENDERER_LIB_SD 
	TOADLET_PEEPER_D3DMRENDERER_LIB_SD 
	TOADLET_PEEPER_D3D10RENDERER_LIB_SD 
	TOADLET_PEEPER_D3D11RENDERER_LIB_SD 
	TOADLET_RIBBIT_LIB_SD 
	TOADLET_RIBBIT_ALPLAYER_LIB_SD 
	TOADLET_RIBBIT_MMPLAYER_LIB_SD 
	TOADLET_TADPOLE_LIB_SD 
	TOADLET_TADPOLE_HOP_LIB_SD 
	TOADLET_PAD_LIB_SD 
)

if (TOADLET_INCLUDE_DIR)
	if (TOADLET_EGG_LIB)
		get_filename_component (TOADLET_LIBRARY_DIR ${TOADLET_EGG_LIB} PATH CACHE)
		set (TOADLET_FOUND "YES")
	elseif (TOADLET_EGG_LIB_D)
		get_filename_component (TOADLET_LIBRARY_DIR ${TOADLET_EGG_LIB_D} PATH CACHE)
		set (TOADLET_FOUND "YES")
	elseif (TOADLET_EGG_LIB_S)
		get_filename_component (TOADLET_LIBRARY_DIR ${TOADLET_EGG_LIB_S} PATH CACHE)
		set (TOADLET_FOUND "YES")
	elseif (TOADLET_EGG_LIB_SD)
		get_filename_component (TOADLET_LIBRARY_DIR ${TOADLET_EGG_LIB_SD} PATH CACHE)
		set (TOADLET_FOUND "YES")
	endif (TOADLET_EGG_LIB)
endif (TOADLET_INCLUDE_DIR)

if (TOADLET_FOUND)
	if (NOT TOADLET_FIND_QUITELY)
		message (STATUS "toadet found")
	endif (NOT TOADLET_FIND_QUITELY)
else (TOADLET_FOUND)
	if (TOADLET_FIND_REQUIRED)
		message (FATAL_ERROR "Could NOT find toadlet")
	endif (TOADLET_FIND_REQUIRED)
	if (NOT TOADLET_FIND_QUITELY)
		message (STATUS "Could NOT find toadlet")
	endif (NOT TOADLET_FIND_QUITELY)
endif (TOADLET_FOUND)

