# Attempt to find toadlet
# Defines:
#
#  TOADLET_FOUND	- system has toadlet
#  TOADLET_INCLUDE_DIR	- path to the toadlet include directory
#  TOADLET_LIBRARY_DIR	- path to the toadlet library installation dir
#
# Also defines each toadlet library individually, both dynamic and static (_S) versions. Release chosen first, then debug (_D):
#  TOADLET_EGG_LIB
#  TOADLET_FLICK_LIB
#  TOADLET_FLICK_HTCMOTIONDEVICE_LIB
#  TOADLET_FLICK_IOSMOTIONDEVICE_LIB
#  TOADLET_FLICK_SAMSUNGMOTIONDEVICE_LIB
#  TOADLET_HOP_LIB
#  TOADLET_KNOT_LIB
#  TOADLET_PEEPER_LIB
#  TOADLET_PEEPER_GLRENDERDEVICE_LIB
#  TOADLET_PEEPER_D3D9RENDERDEVICE_LIB
#  TOADLET_PEEPER_D3DMRENDERDEVICE_LIB
#  TOADLET_PEEPER_D3D10RENDERDEVICE_LIB
#  TOADLET_PEEPER_D3D11RENDERDEVICE_LIB
#  TOADLET_RIBBIT_LIB
#  TOADLET_RIBBIT_ALAUIODEVICE_LIB
#  TOADLET_RIBBIT_MMAUIODEVICE_LIB
#  TOADLET_TADPOLE_LIB
#  TOADLET_TADPOLE_HOP_LIB
#  TOADLET_PAD_LIB
# 
# NOTE: If release libraries are not found, they will be set to the debug libraries. The reverse is NOT true.

set (TOADLET_FOUND "NO")

# Default search paths
if (WIN32)
	set (HEADER_SEARCH_PATHS
		"C:/Program Files"
		"C:/Program Files/toadlet"
	)
	set (LIBRARY_SEARCH_PATHS
		"C:/Program Files"
		"C:/Program Files/toadlet"
	)
else (WIN32)
	set (HEADER_SEARCH_PATHS
		/usr/include
		/usr/local/include

	)
	set (LIBRARY_SEARCH_PATHS
		/usr/lib 
		/usr/local/lib
	)
endif (WIN32)

# Headers
find_path (TOADLET_INCLUDE_DIR toadlet/toadlet.h PATHS ${HEADER_SEARCH_PATHS})

# Dynamic Libraries
find_library (TOADLET_EGG_LIB NAMES toadlet_egg PATHS ${LIBRARY_SEARCH_PATHS})
find_library (TOADLET_FLICK_LIB NAMES toadlet_flick PATHS ${LIBRARY_SEARCH_PATHS})
find_library (TOADLET_FLICK_HTCMOTIONDEVICE_LIB NAMES toadlet_flick_htcmotiondevice PATHS ${LIBRARY_SEARCH_PATHS})
find_library (TOADLET_FLICK_IOSMOTIONDEVICE_LIB NAMES toadlet_flick_iosmotiondevice PATHS ${LIBRARY_SEARCH_PATHS})
find_library (TOADLET_FLICK_SAMSUNGMOTIONDEVICE_LIB NAMES toadlet_flick_samsungmotiondevice PATHS ${LIBRARY_SEARCH_PATHS})
find_library (TOADLET_HOP_LIB NAMES toadlet_hop PATHS ${LIBRARY_SEARCH_PATHS})
find_library (TOADLET_KNOT_LIB NAMES toadlet_knot PATHS ${LIBRARY_SEARCH_PATHS})
find_library (TOADLET_PEEPER_LIB NAMES toadlet_peeper PATHS ${LIBRARY_SEARCH_PATHS})
find_library (TOADLET_PEEPER_GLRENDERDEVICE_LIB NAMES toadlet_peeper_glrenderdevice PATHS ${LIBRARY_SEARCH_PATHS})
find_library (TOADLET_PEEPER_D3D9RENDERDEVICE_LIB NAMES toadlet_peeper_d3d9renderdevice PATHS ${LIBRARY_SEARCH_PATHS})
find_library (TOADLET_PEEPER_D3DMRENDERDEVICE_LIB NAMES toadlet_peeper_d3dmrenderdevice PATHS ${LIBRARY_SEARCH_PATHS})
find_library (TOADLET_PEEPER_D3D10RENDERDEVICE_LIB NAMES toadlet_peeper_d3d10renderdevice PATHS ${LIBRARY_SEARCH_PATHS})
find_library (TOADLET_PEEPER_D3D11RENDERDEVICE_LIB NAMES toadlet_peeper_d3d11renderdevice PATHS ${LIBRARY_SEARCH_PATHS})
find_library (TOADLET_RIBBIT_LIB NAMES toadlet_ribbit PATHS ${LIBRARY_SEARCH_PATHS})
find_library (TOADLET_RIBBIT_ALAUIODEVICE_LIB NAMES toadlet_ribbit_alaudiodevice PATHS ${LIBRARY_SEARCH_PATHS})
find_library (TOADLET_RIBBIT_MMAUIODEVICE_LIB NAMES toadlet_ribbit_mmaudiodevice PATHS ${LIBRARY_SEARCH_PATHS})
find_library (TOADLET_TADPOLE_LIB NAMES toadlet_tadpole PATHS ${LIBRARY_SEARCH_PATHS})
find_library (TOADLET_TADPOLE_HOP_LIB NAMES toadlet_tadpole_hop PATHS ${LIBRARY_SEARCH_PATHS})
find_library (TOADLET_PAD_LIB NAMES toadlet_pad PATHS ${LIBRARY_SEARCH_PATHS})

# Dynamic Libraries - debug
find_library (TOADLET_EGG_LIB_D NAMES toadlet_egg_d PATHS ${LIBRARY_SEARCH_PATHS})
find_library (TOADLET_FLICK_LIB_D NAMES toadlet_flick_d PATHS ${LIBRARY_SEARCH_PATHS})
find_library (TOADLET_FLICK_HTCMOTIONDEVICE_LIB_D NAMES toadlet_flick_htcmotiondevice_d PATHS ${LIBRARY_SEARCH_PATHS})
find_library (TOADLET_FLICK_IOSMOTIONDEVICE_LIB_D NAMES toadlet_flick_iosmotiondevice_d PATHS ${LIBRARY_SEARCH_PATHS})
find_library (TOADLET_FLICK_SAMSUNGMOTIONDEVICE_LIB_D NAMES toadlet_flick_samsungmotiondevice_d PATHS ${LIBRARY_SEARCH_PATHS})
find_library (TOADLET_HOP_LIB_D NAMES toadlet_hop_d PATHS ${LIBRARY_SEARCH_PATHS})
find_library (TOADLET_KNOT_LIB_D NAMES toadlet_knot_d PATHS ${LIBRARY_SEARCH_PATHS})
find_library (TOADLET_PEEPER_LIB_D NAMES toadlet_peeper_d PATHS ${LIBRARY_SEARCH_PATHS})
find_library (TOADLET_PEEPER_GLRENDERDEVICE_LIB_D NAMES toadlet_peeper_glrenderdevice_d PATHS ${LIBRARY_SEARCH_PATHS})
find_library (TOADLET_PEEPER_D3D9RENDERDEVICE_LIB_D NAMES toadlet_peeper_d3d9renderdevice_d PATHS ${LIBRARY_SEARCH_PATHS})
find_library (TOADLET_PEEPER_D3DMRENDERDEVICE_LIB_D NAMES toadlet_peeper_d3dmrenderdevice_d PATHS ${LIBRARY_SEARCH_PATHS})
find_library (TOADLET_PEEPER_D3D10RENDERDEVICE_LIB_D NAMES toadlet_peeper_d3d10renderdevice_d PATHS ${LIBRARY_SEARCH_PATHS})
find_library (TOADLET_PEEPER_D3D11RENDERDEVICE_LIB_D NAMES toadlet_peeper_d3d11renderdevice_d PATHS ${LIBRARY_SEARCH_PATHS})
find_library (TOADLET_RIBBIT_LIB_D NAMES toadlet_ribbit_d PATHS ${LIBRARY_SEARCH_PATHS})
find_library (TOADLET_RIBBIT_ALAUIODEVICE_LIB_D NAMES toadlet_ribbit_alaudiodevice_d PATHS ${LIBRARY_SEARCH_PATHS})
find_library (TOADLET_RIBBIT_MMAUIODEVICE_LIB_D NAMES toadlet_ribbit_mmaudiodevice_d PATHS ${LIBRARY_SEARCH_PATHS})
find_library (TOADLET_TADPOLE_LIB_D NAMES toadlet_tadpole_d PATHS ${LIBRARY_SEARCH_PATHS})
find_library (TOADLET_TADPOLE_HOP_LIB_D NAMES toadlet_tadpole_hop_d PATHS ${LIBRARY_SEARCH_PATHS})
find_library (TOADLET_PAD_LIB_D NAMES toadlet_pad_d PATHS ${LIBRARY_SEARCH_PATHS})

# If release libraries are not found, they will be set to the debug libraries. The reverse is NOT true.
if (NOT TOADLET_EGG_LIB)
	set (TOADLET_EGG_LIB ${TOADLET_EGG_LIB_D})
endif (NOT TOADLET_EGG_LIB)
if (NOT TOADLET_FLICK_LIB)
	set (TOADLET_FLICK_LIB ${TOADLET_FLICK_LIB_D})
endif (NOT TOADLET_FLICK_LIB)
if (NOT TOADLET_FLICK_HTCMOTIONDEVICE_LIB)
	set (TOADLET_FLICK_HTCMOTIONDEVICE_LIB ${TOADLET_FLICK_HTCMOTIONDEVICE_LIB_D})
endif (NOT TOADLET_FLICK_HTCMOTIONDEVICE_LIB)
if (NOT TOADLET_FLICK_IOSMOTIONDEVICE_LIB)
	set (TOADLET_FLICK_IOSMOTIONDEVICE_LIB ${TOADLET_FLICK_IOSMOTIONDEVICE_LIB_D})
endif (NOT TOADLET_FLICK_IOSMOTIONDEVICE_LIB)
if (NOT TOADLET_FLICK_SAMSUNGSMOTIONDEVICE_LIB)
	set (TOADLET_FLICK_SAMSUNGSMOTIONDEVICE_LIB ${TOADLET_FLICK_SAMSUNGSMOTIONDEVICE_LIB_D})
endif (NOT TOADLET_FLICK_SAMSUNGSMOTIONDEVICE_LIB)
if (NOT TOADLET_HOP_LIB)
	set (TOADLET_HOP_LIB ${TOADLET_HOP_LIB_D})
endif (NOT TOADLET_HOP_LIB)
if (NOT TOADLET_KNOT_LIB)
	set (TOADLET_KNOT_LIB ${TOADLET_KNOT_LIB_D})
endif (NOT TOADLET_KNOT_LIB)
if (NOT TOADLET_PEEPER_LIB)
	set (TOADLET_PEEPER_LIB ${TOADLET_PEEPER_LIB_D})
 endif (NOT TOADLET_PEEPER_LIB)
if (NOT TOADLET_PEEPER_GLRENDERDEVICE_LIB)
	set (TOADLET_PEEPER_GLRENDERDEVICE_LIB ${TOADLET_PEEPER_GLRENDERDEVICE_LIB_D})
endif (NOT TOADLET_PEEPER_GLRENDERDEVICE_LIB)
if (NOT TOADLET_PEEPER_D3D9RENDERDEVICE_LIB)
	set (TOADLET_PEEPER_D3D9RENDERDEVICE_LIB ${TOADLET_PEEPER_D3D9RENDERDEVICE_LIB_D})
endif (NOT TOADLET_PEEPER_D3D9RENDERDEVICE_LIB)
if (NOT TOADLET_PEEPER_D3D10RENDERDEVICE_LIB)
	set (TOADLET_PEEPER_D3D10RENDERDEVICE_LIB ${TOADLET_PEEPER_D3D10RENDERDEVICE_LIB_D})
endif (NOT TOADLET_PEEPER_D3D10RENDERDEVICE_LIB)
if (NOT TOADLET_PEEPER_D3D11RENDERDEVICE_LIB)
	set (TOADLET_PEEPER_D3D11RENDERDEVICE_LIB ${TOADLET_PEEPER_D3D11RENDERDEVICE_LIB_D})
endif (NOT TOADLET_PEEPER_D3D11RENDERDEVICE_LIB)
if (NOT TOADLET_RIBBIT_LIB)
	set (TOADLET_RIBBIT_LIB ${TOADLET_RIBBIT_LIB_D})
endif (NOT TOADLET_RIBBIT_LIB)
if (NOT TOADLET_RIBBIT_ALAUIODEVICE_LIB)
	set (TOADLET_RIBBIT_ALAUIODEVICE_LIB ${TOADLET_RIBBIT_ALAUIODEVICE_LIB_D})
endif (NOT TOADLET_RIBBIT_ALAUIODEVICE_LIB)
if (NOT TOADLET_RIBBIT_NMAUIODEVICE_LIB)
	set (TOADLET_RIBBIT_NMAUIODEVICE_LIB ${TOADLET_RIBBIT_NMAUIODEVICE_LIB_D})
endif (NOT TOADLET_RIBBIT_NMAUIODEVICE_LIB)
if (NOT TOADLET_TADPOLE_LIB)
	set (TOADLET_TADPOLE_LIB ${TOADLET_TADPOLE_LIB_D})
endif (NOT TOADLET_TADPOLE_LIB)
if (NOT TOADLET_TADPOLE_HOP_LIB)
	set (TOADLET_TADPOLE_HOP_LIB ${TOADLET_TADPOLE_HOP_LIB_D})
endif (NOT TOADLET_TADPOLE_HOP_LIB)
if (NOT TOADLET_PAD_LIB)
	set (TOADLET_PAD_LIB ${TOADLET_PAD_LIB_D})
endif (NOT TOADLET_PAD_LIB)

# Static Libraries
find_library (TOADLET_EGG_LIB_S NAMES toadlet_egg_s PATHS ${LIBRARY_SEARCH_PATHS})
find_library (TOADLET_FLICK_LIB_S NAMES toadlet_flick_s PATHS ${LIBRARY_SEARCH_PATHS})
find_library (TOADLET_FLICK_HTCMOTIONDEVICE_LIB_S NAMES toadlet_flick_htcmotiondevice_s PATHS ${LIBRARY_SEARCH_PATHS})
find_library (TOADLET_FLICK_IOSMOTIONDEVICE_LIB_S NAMES toadlet_flick_iosmotiondevice_s PATHS ${LIBRARY_SEARCH_PATHS})
find_library (TOADLET_FLICK_SAMSUNGMOTIONDEVICE_LIB_S NAMES toadlet_flick_samsungmotiondevice_s PATHS ${LIBRARY_SEARCH_PATHS})
find_library (TOADLET_HOP_LIB_S NAMES toadlet_hop_s PATHS ${LIBRARY_SEARCH_PATHS})
find_library (TOADLET_KNOT_LIB_S NAMES toadlet_knot_s PATHS ${LIBRARY_SEARCH_PATHS})
find_library (TOADLET_PEEPER_LIB_S NAMES toadlet_peeper_s PATHS ${LIBRARY_SEARCH_PATHS})
find_library (TOADLET_PEEPER_GLRENDERDEVICE_LIB_S NAMES toadlet_peeper_glrenderdevice_s PATHS ${LIBRARY_SEARCH_PATHS})
find_library (TOADLET_PEEPER_D3D9RENDERDEVICE_LIB_S NAMES toadlet_peeper_d3d9renderdevice_s PATHS ${LIBRARY_SEARCH_PATHS})
find_library (TOADLET_PEEPER_D3DMRENDERDEVICE_LIB_S NAMES toadlet_peeper_d3dmrenderdevice_s PATHS ${LIBRARY_SEARCH_PATHS})
find_library (TOADLET_PEEPER_D3D10RENDERDEVICE_LIB_S NAMES toadlet_peeper_d3d10renderdevice_s PATHS ${LIBRARY_SEARCH_PATHS})
find_library (TOADLET_PEEPER_D3D11RENDERDEVICE_LIB_S NAMES toadlet_peeper_d3d11renderdevice_s PATHS ${LIBRARY_SEARCH_PATHS})
find_library (TOADLET_RIBBIT_LIB_S NAMES toadlet_ribbit_s PATHS ${LIBRARY_SEARCH_PATHS})
find_library (TOADLET_RIBBIT_ALAUIODEVICE_LIB_S NAMES toadlet_ribbit_alaudiodevice_s PATHS ${LIBRARY_SEARCH_PATHS})
find_library (TOADLET_RIBBIT_MMAUIODEVICE_LIB_S NAMES toadlet_ribbit_mmaudiodevice_s PATHS ${LIBRARY_SEARCH_PATHS})
find_library (TOADLET_TADPOLE_LIB_S NAMES toadlet_tadpole_s PATHS ${LIBRARY_SEARCH_PATHS})
find_library (TOADLET_TADPOLE_HOP_LIB_S NAMES toadlet_tadpole_hop_s PATHS ${LIBRARY_SEARCH_PATHS})
find_library (TOADLET_PAD_LIB_S NAMES toadlet_pad_s PATHS ${LIBRARY_SEARCH_PATHS})

# Static Libraries - debug
find_library (TOADLET_EGG_LIB_SD NAMES toadlet_egg_sd PATHS ${LIBRARY_SEARCH_PATHS})
find_library (TOADLET_FLICK_LIB_SD NAMES toadlet_flick_sd PATHS ${LIBRARY_SEARCH_PATHS})
find_library (TOADLET_FLICK_HTCMOTIONDEVICE_LIB_SD NAMES toadlet_flick_htcmotiondevice_sd PATHS ${LIBRARY_SEARCH_PATHS})
find_library (TOADLET_FLICK_IOSMOTIONDEVICE_LIB_SD NAMES toadlet_flick_iosmotiondevice_sd PATHS ${LIBRARY_SEARCH_PATHS})
find_library (TOADLET_FLICK_SAMSUNGMOTIONDEVICE_LIB_SD NAMES toadlet_flick_samsungmotiondevice_sd PATHS ${LIBRARY_SEARCH_PATHS})
find_library (TOADLET_HOP_LIB_SD NAMES toadlet_hop_sd PATHS ${LIBRARY_SEARCH_PATHS})
find_library (TOADLET_KNOT_LIB_SD NAMES toadlet_knot_sd PATHS ${LIBRARY_SEARCH_PATHS})
find_library (TOADLET_PEEPER_LIB_SD NAMES toadlet_peeper_sd PATHS ${LIBRARY_SEARCH_PATHS})
find_library (TOADLET_PEEPER_GLRENDERDEVICE_LIB_SD NAMES toadlet_peeper_glrenderdevice_sd PATHS ${LIBRARY_SEARCH_PATHS})
find_library (TOADLET_PEEPER_D3D9RENDERDEVICE_LIB_SD NAMES toadlet_peeper_d3d9renderdevice_sd PATHS ${LIBRARY_SEARCH_PATHS})
find_library (TOADLET_PEEPER_D3DMRENDERDEVICE_LIB_SD NAMES toadlet_peeper_d3dmrenderdevice_sd PATHS ${LIBRARY_SEARCH_PATHS})
find_library (TOADLET_PEEPER_D3D10RENDERDEVICE_LIB_SD NAMES toadlet_peeper_d3d10renderdevice_sd PATHS ${LIBRARY_SEARCH_PATHS})
find_library (TOADLET_PEEPER_D3D11RENDERDEVICE_LIB_SD NAMES toadlet_peeper_d3d11renderdevice_sd PATHS ${LIBRARY_SEARCH_PATHS})
find_library (TOADLET_RIBBIT_LIB_SD NAMES toadlet_ribbit_sd PATHS ${LIBRARY_SEARCH_PATHS})
find_library (TOADLET_RIBBIT_ALAUIODEVICE_LIB_SD NAMES toadlet_ribbit_alaudiodevice_sd PATHS ${LIBRARY_SEARCH_PATHS})
find_library (TOADLET_RIBBIT_MMAUIODEVICE_LIB_SD NAMES toadlet_ribbit_mmaudiodevice_sd PATHS ${LIBRARY_SEARCH_PATHS})
find_library (TOADLET_TADPOLE_LIB_SD NAMES toadlet_tadpole_sd PATHS ${LIBRARY_SEARCH_PATHS})
find_library (TOADLET_TADPOLE_HOP_LIB_SD NAMES toadlet_tadpole_hop_sd PATHS ${LIBRARY_SEARCH_PATHS})
find_library (TOADLET_PAD_LIB_SD NAMES toadlet_pad_sd PATHS ${LIBRARY_SEARCH_PATHS})

# If release libraries are not found, they will be set to the debug libraries. The reverse is NOT true.
if (NOT TOADLET_EGG_LIB_S)
	set (TOADLET_EGG_LIB_S ${TOADLET_EGG_LIB_SD})
endif (NOT TOADLET_EGG_LIB_S)
if (NOT TOADLET_FLICK_LIB_S)
	set (TOADLET_FLICK_LIB_S ${TOADLET_FLICK_LIB_SD})
endif (NOT TOADLET_FLICK_LIB_S)
if (NOT TOADLET_FLICK_HTCMOTIONDEVICE_LIB_S)
	set (TOADLET_FLICK_HTCMOTIONDEVICE_LIB_S ${TOADLET_FLICK_HTCMOTIONDEVICE_LIB_SD})
endif (NOT TOADLET_FLICK_HTCMOTIONDEVICE_LIB_S)
if (NOT TOADLET_FLICK_IOSMOTIONDEVICE_LIB_S)
	set (TOADLET_FLICK_IOSMOTIONDEVICE_LIB_S ${TOADLET_FLICK_IOSMOTIONDEVICE_LIB_SD})
endif (NOT TOADLET_FLICK_IOSMOTIONDEVICE_LIB_S)
if (NOT TOADLET_FLICK_SAMSUNGSMOTIONDEVICE_LIB_S)
	set (TOADLET_FLICK_SAMSUNGSMOTIONDEVICE_LIB_S ${TOADLET_FLICK_SAMSUNGSMOTIONDEVICE_LIB_SD})
endif (NOT TOADLET_FLICK_SAMSUNGSMOTIONDEVICE_LIB_S)
if (NOT TOADLET_HOP_LIB_S)
	set (TOADLET_HOP_LIB_S ${TOADLET_HOP_LIB_SD})
endif (NOT TOADLET_HOP_LIB_S)
if (NOT TOADLET_KNOT_LIB_S)
	set (TOADLET_KNOT_LIB_S ${TOADLET_KNOT_LIB_SD})
endif (NOT TOADLET_KNOT_LIB_S)
if (NOT TOADLET_PEEPER_LIB_S)
	set (TOADLET_PEEPER_LIB_S ${TOADLET_PEEPER_LIB_SD})
 endif (NOT TOADLET_PEEPER_LIB_S)
if (NOT TOADLET_PEEPER_GLRENDERDEVICE_LIB_S)
	set (TOADLET_PEEPER_GLRENDERDEVICE_LIB_S ${TOADLET_PEEPER_GLRENDERDEVICE_LIB_SD})
endif (NOT TOADLET_PEEPER_GLRENDERDEVICE_LIB_S)
if (NOT TOADLET_PEEPER_D3D9RENDERDEVICE_LIB_S)
	set (TOADLET_PEEPER_D3D9RENDERDEVICE_LIB_S ${TOADLET_PEEPER_D3D9RENDERDEVICE_LIB_SD})
endif (NOT TOADLET_PEEPER_D3D9RENDERDEVICE_LIB_S)
if (NOT TOADLET_PEEPER_D3D10RENDERDEVICE_LIB_S)
	set (TOADLET_PEEPER_D3D10RENDERDEVICE_LIB_S ${TOADLET_PEEPER_D3D10RENDERDEVICE_LIB_SD})
endif (NOT TOADLET_PEEPER_D3D10RENDERDEVICE_LIB_S)
if (NOT TOADLET_PEEPER_D3D11RENDERDEVICE_LIB_S)
	set (TOADLET_PEEPER_D3D11RENDERDEVICE_LIB_S ${TOADLET_PEEPER_D3D11RENDERDEVICE_LIB_SD})
endif (NOT TOADLET_PEEPER_D3D11RENDERDEVICE_LIB_S)
if (NOT TOADLET_RIBBIT_LIB_S)
	set (TOADLET_RIBBIT_LIB_S ${TOADLET_RIBBIT_LIB_SD})
endif (NOT TOADLET_RIBBIT_LIB_S)
if (NOT TOADLET_RIBBIT_ALAUIODEVICE_LIB_S)
	set (TOADLET_RIBBIT_ALAUIODEVICE_LIB_S ${TOADLET_RIBBIT_ALAUIODEVICE_LIB_SD})
endif (NOT TOADLET_RIBBIT_ALAUIODEVICE_LIB_S)
if (NOT TOADLET_RIBBIT_NMAUIODEVICE_LIB_S)
	set (TOADLET_RIBBIT_NMAUIODEVICE_LIB_S ${TOADLET_RIBBIT_NMAUIODEVICE_LIB_SD})
endif (NOT TOADLET_RIBBIT_NMAUIODEVICE_LIB_S)
if (NOT TOADLET_TADPOLE_LIB_S)
	set (TOADLET_TADPOLE_LIB_S ${TOADLET_TADPOLE_LIB_SD})
endif (NOT TOADLET_TADPOLE_LIB_S)
if (NOT TOADLET_TADPOLE_HOP_LIB_S)
	set (TOADLET_TADPOLE_HOP_LIB_S ${TOADLET_TADPOLE_HOP_LIB_SD})
endif (NOT TOADLET_TADPOLE_HOP_LIB_S)
if (NOT TOADLET_PAD_LIB_S)
	set (TOADLET_PAD_LIB_S ${TOADLET_PAD_LIB_SD})
endif (NOT TOADLET_PAD_LIB_S)


# Prevent these from appearing in the regular variable list
mark_as_advanced (
	TOADLET_INCLUDE_DIR
	TOADLET_LIBRARY_DIR
	TOADLET_EGG_LIB 
	TOADLET_FLICK_LIB 
	TOADLET_FLICK_HTCMOTIONDEVICE_LIB 
	TOADLET_FLICK_IOSMOTIONDEVICE_LIB 
	TOADLET_FLICK_SAMSUNGMOTIONDEVICE_LIB 
	TOADLET_HOP_LIB 
	TOADLET_KNOT_LIB 
	TOADLET_PEEPER_LIB 
	TOADLET_PEEPER_GLRENDERDEVICE_LIB 
	TOADLET_PEEPER_D3D9RENDERDEVICE_LIB 
	TOADLET_PEEPER_D3DMRENDERDEVICE_LIB 
	TOADLET_PEEPER_D3D10RENDERDEVICE_LIB 
	TOADLET_PEEPER_D3D11RENDERDEVICE_LIB 
	TOADLET_RIBBIT_LIB 
	TOADLET_RIBBIT_ALAUIODEVICE_LIB 
	TOADLET_RIBBIT_MMAUIODEVICE_LIB 
	TOADLET_TADPOLE_LIB 
	TOADLET_TADPOLE_HOP_LIB 
	TOADLET_PAD_LIB 
	TOADLET_EGG_LIB_D 
	TOADLET_FLICK_LIB_D 
	TOADLET_FLICK_HTCMOTIONDEVICE_LIB_D 
	TOADLET_FLICK_IOSMOTIONDEVICE_LIB_D 
	TOADLET_FLICK_SAMSUNGMOTIONDEVICE_LIB_D 
	TOADLET_HOP_LIB_D 
	TOADLET_KNOT_LIB_D 
	TOADLET_PEEPER_LIB_D 
	TOADLET_PEEPER_GLRENDERDEVICE_LIB_D 
	TOADLET_PEEPER_D3D9RENDERDEVICE_LIB_D 
	TOADLET_PEEPER_D3DMRENDERDEVICE_LIB_D 
	TOADLET_PEEPER_D3D10RENDERDEVICE_LIB_D 
	TOADLET_PEEPER_D3D11RENDERDEVICE_LIB_D 
	TOADLET_RIBBIT_LIB_D 
	TOADLET_RIBBIT_ALAUIODEVICE_LIB_D 
	TOADLET_RIBBIT_MMAUIODEVICE_LIB_D 
	TOADLET_TADPOLE_LIB_D 
	TOADLET_TADPOLE_HOP_LIB_D 
	TOADLET_PAD_LIB_D 
	TOADLET_EGG_LIB_S 
	TOADLET_FLICK_LIB_S 
	TOADLET_FLICK_HTCMOTIONDEVICE_LIB_S 
	TOADLET_FLICK_IOSMOTIONDEVICE_LIB_S 
	TOADLET_FLICK_SAMSUNGMOTIONDEVICE_LIB_S 
	TOADLET_HOP_LIB_S 
	TOADLET_KNOT_LIB_S 
	TOADLET_PEEPER_LIB_S 
	TOADLET_PEEPER_GLRENDERDEVICE_LIB_S 
	TOADLET_PEEPER_D3D9RENDERDEVICE_LIB_S 
	TOADLET_PEEPER_D3DMRENDERDEVICE_LIB_S 
	TOADLET_PEEPER_D3D10RENDERDEVICE_LIB_S 
	TOADLET_PEEPER_D3D11RENDERDEVICE_LIB_S 
	TOADLET_RIBBIT_LIB_S 
	TOADLET_RIBBIT_ALAUIODEVICE_LIB_S 
	TOADLET_RIBBIT_MMAUIODEVICE_LIB_S 
	TOADLET_TADPOLE_LIB_S 
	TOADLET_TADPOLE_HOP_LIB_S 
	TOADLET_PAD_LIB_S 
	TOADLET_EGG_LIB_SD 
	TOADLET_FLICK_LIB_SD 
	TOADLET_FLICK_HTCMOTIONDEVICE_LIB_SD 
	TOADLET_FLICK_IOSMOTIONDEVICE_LIB_SD 
	TOADLET_FLICK_SAMSUNGMOTIONDEVICE_LIB_SD 
	TOADLET_HOP_LIB_SD 
	TOADLET_KNOT_LIB_SD 
	TOADLET_PEEPER_LIB_SD 
	TOADLET_PEEPER_GLRENDERDEVICE_LIB_SD 
	TOADLET_PEEPER_D3D9RENDERDEVICE_LIB_SD 
	TOADLET_PEEPER_D3DMRENDERDEVICE_LIB_SD 
	TOADLET_PEEPER_D3D10RENDERDEVICE_LIB_SD 
	TOADLET_PEEPER_D3D11RENDERDEVICE_LIB_SD 
	TOADLET_RIBBIT_LIB_SD 
	TOADLET_RIBBIT_ALAUIODEVICE_LIB_SD 
	TOADLET_RIBBIT_MMAUIODEVICE_LIB_SD 
	TOADLET_TADPOLE_LIB_SD 
	TOADLET_TADPOLE_HOP_LIB_SD 
	TOADLET_PAD_LIB_SD 
)

if (TOADLET_INCLUDE_DIR)
	if (TOADLET_EGG_LIB)
		get_filename_component (TOADLET_LIBRARY_DIR ${TOADLET_EGG_LIB} PATH CACHE)
		set (TOADLET_FOUND "YES")
	elseif (TOADLET_EGG_LIB_D)
		get_filename_component (TOADLET_LIBRARY_DIR ${TOADLET_EGG_LIB_D} PATH CACHE)
		set (TOADLET_FOUND "YES")
	elseif (TOADLET_EGG_LIB_S)
		get_filename_component (TOADLET_LIBRARY_DIR ${TOADLET_EGG_LIB_S} PATH CACHE)
		set (TOADLET_FOUND "YES")
	elseif (TOADLET_EGG_LIB_SD)
		get_filename_component (TOADLET_LIBRARY_DIR ${TOADLET_EGG_LIB_SD} PATH CACHE)
		set (TOADLET_FOUND "YES")
	endif (TOADLET_EGG_LIB)
endif (TOADLET_INCLUDE_DIR)

if (TOADLET_FOUND)
	if (NOT TOADLET_FIND_QUITELY)
		message (STATUS "toadet found")
	endif (NOT TOADLET_FIND_QUITELY)
else (TOADLET_FOUND)
	if (TOADLET_FIND_REQUIRED)
		message (FATAL_ERROR "Could NOT find toadlet")
	endif (TOADLET_FIND_REQUIRED)
	if (NOT TOADLET_FIND_QUITELY)
		message (STATUS "Could NOT find toadlet")
	endif (NOT TOADLET_FIND_QUITELY)
endif (TOADLET_FOUND)

