set (FFMPEG_FOUND "NO")
set (FFMPEG_LIBRARIES "")

if (WIN32)
	set (HDR_SEARCH_PATHS
        "C:/Program Files/ffmpeg/include"
	)
	set (LIB_SEARCH_PATHS
        "C:/Program Files/ffmpeg/lib"
	)
	set (EXE_SEARCH_PATHS
        "C:/Program Files/ffmpeg/bin"
	)
else (WIN32)
	set (HDR_SEARCH_PATHS
        /usr/include
        /usr/local/include
	)
	set (LIB_SEARCH_PATHS
        /usr/lib
        /usr/local/lib
	)
	set (EXE_SEARCH_PATHS
        /usr/bin
        /usr/local/bin
	)
endif (WIN32)

find_program (FFMPEG_EXE NAMES ffmpeg ffmpeg.exe PATHS ${EXE_SEARCH_PATHS})
find_path (FFMPEG_INCLUDE_DIR libavcodec/avcodec.h PATHS ${HDR_SEARCH_PATHS})
find_library (AVCODEC_LIBRARY NAMES avcodec PATHS ${LIB_SEARCH_PATHS})
find_library (AVDEVICE_LIBRARY NAMES avdevice PATHS ${LIB_SEARCH_PATHS})
find_library (AVFILTER_LIBRARY NAMES avfilter PATHS ${LIB_SEARCH_PATHS})
find_library (AVFORMAT_LIBRARY NAMES avformat PATHS ${LIB_SEARCH_PATHS})
find_library (AVUTIL_LIBRARY NAMES avutil PATHS ${LIB_SEARCH_PATHS})
find_library (POSTPROC_LIBRARY NAMES postproc PATHS ${LIB_SEARCH_PATHS})
find_library (SWRESAMPLE_LIBRARY NAMES swresample PATHS ${LIB_SEARCH_PATHS})
find_library (SWSCALE_LIBRARY NAMES swscale PATHS ${LIB_SEARCH_PATHS})

if (AVCODEC_LIBRARY)
	set (FFMPEG_LIBRARIES ${FFMPEG_LIBRARIES} ${AVCODEC_LIBRARY})
endif (AVCODEC_LIBRARY)
if (AVDEVICE_LIBRARY)
	set (FFMPEG_LIBRARIES ${FFMPEG_LIBRARIES} ${AVDEVICE_LIBRARY})
endif (AVDEVICE_LIBRARY)
if (AVFILTER_LIBRARY)
	set (FFMPEG_LIBRARIES ${FFMPEG_LIBRARIES} ${AVFILTER_LIBRARY})
endif (AVFILTER_LIBRARY)
if (AVFORMAT_LIBRARY)
	set (FFMPEG_LIBRARIES ${FFMPEG_LIBRARIES} ${AVFORMAT_LIBRARY})
endif (AVFORMAT_LIBRARY)
if (AVUTIL_LIBRARY)
	set (FFMPEG_LIBRARIES ${FFMPEG_LIBRARIES} ${AVUTIL_LIBRARY})
endif (AVUTIL_LIBRARY)
if (POSTPROC_LIBRARY)
	set (FFMPEG_LIBRARIES ${FFMPEG_LIBRARIES} ${POSTPROC_LIBRARY})
endif (POSTPROC_LIBRARY)
if (SWRESAMPLE_LIBRARY)
	set (FFMPEG_LIBRARIES ${FFMPEG_LIBRARIES} ${SWRESAMPLE_LIBRARY})
endif (SWRESAMPLE_LIBRARY)
if (SWSCALE_LIBRARY)
	set (FFMPEG_LIBRARIES ${FFMPEG_LIBRARIES} ${SWSCALE_LIBRARY})
endif (SWSCALE_LIBRARY)

mark_as_advanced (FFMPEG_EXE FFMPEG_INCLUDE_DIR FFMPEG_LIBRARIES AVCODEC_LIBRARY AVDEVICE_LIBRARY AVFILTER_LIBRARY AVFORMAT_LIBRARY AVUTIL_LIBRARY POSTPROC_LIBRARY SWRESAMPLE_LIBRARY SWSCALE_LIBRARY)

message (STATUS "FFmpeg executable : ${FFMPEG_EXE}")
message (STATUS "FFmpeg include dir: ${FFMPEG_INCLUDE_DIR}")
message (STATUS "FFmpeg libraries: ${FFMPEG_LIBRARIES}")

set (FFMPEG_EXE ${FFMPEG_EXE} CACHE FILEPATH "FFmpeg executable" FORCE)
set (FFMPEG_INCLUDE_DIR ${FFMPEG_INCLUDE_DIR} CACHE PATH "FFmpeg include folder" FORCE)
set (FFMPEG_LIBRARIES ${FFMPEG_LIBRARIES} CACHE FILEPATH "All FFmpeg related libraries" FORCE)

if (FFMPEG_EXE AND FFMPEG_INCLUDE_DIR AND FFMPEG_LIBRARIES)
	set (FFMPEG_FOUND "YES")
endif (FFMPEG_EXE AND FFMPEG_INCLUDE_DIR AND FFMPEG_LIBRARIES)

if (FFMPEG_FOUND)
	if (NOT FFMPEG_FIND_QUITELY)
		message (STATUS "FFMPEG found")
	endif (NOT FFMPEG_FIND_QUITELY)
else (FFMPEG_FOUND)
	if (FFMPEG_FIND_REQUIRED)
		message (FATAL_ERROR "Could NOT find FFMPEG")
	endif (FFMPEG_FIND_REQUIRED)
	if (NOT FFMPEG_FIND_QUITELY)
		message (STATUS "Could NOT find FFMPEG")
	endif (NOT FFMPEG_FIND_QUITELY)
endif (FFMPEG_FOUND)

