/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class us_toadlet_ribbit_NAudioStream */

#ifndef _Included_us_toadlet_ribbit_NAudioStream
#define _Included_us_toadlet_ribbit_NAudioStream
#ifdef __cplusplus
extern "C" {
#endif
#undef us_toadlet_ribbit_NAudioStream_SKIP_BUFFER_SIZE
#define us_toadlet_ribbit_NAudioStream_SKIP_BUFFER_SIZE 2048L
/*
 * Class:     us_toadlet_ribbit_NAudioStream
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_us_toadlet_ribbit_NAudioStream_close
  (JNIEnv *, jobject);

/*
 * Class:     us_toadlet_ribbit_NAudioStream
 * Method:    getAudioFormat
 * Signature: ()Lus/toadlet/ribbit/AudioFormat;
 */
JNIEXPORT jobject JNICALL Java_us_toadlet_ribbit_NAudioStream_getAudioFormat
  (JNIEnv *, jobject);

/*
 * Class:     us_toadlet_ribbit_NAudioStream
 * Method:    available
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_us_toadlet_ribbit_NAudioStream_available
  (JNIEnv *, jobject);

/*
 * Class:     us_toadlet_ribbit_NAudioStream
 * Method:    read
 * Signature: ([BII)I
 */
JNIEXPORT jint JNICALL Java_us_toadlet_ribbit_NAudioStream_read
  (JNIEnv *, jobject, jbyteArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
